/**
 * Estate Manager Shared Status Enums
 */

const ACCESS_CONTROL_STATUS = {
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED'
};

const ACCESS_CODE_TYPES = {
  GUEST: 'GUEST',
  DELIVERY: 'DELIVERY',
  SERVICE: 'SERVICE',
  FREQUENT: 'FREQUENT',
  EVENT: 'EVENT'
};

const ACCESS_CODE_STATUS = {
  ACTIVE: 'ACTIVE',
  USED: 'USED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  RESTRICTED: 'RESTRICTED'
};

const PROPERTY_TYPES = {
  APARTMENT: 'APARTMENT',
  TERRACE: 'TERRACE',
  SEMI_DETACHED: 'SEMI_DETACHED',
  DETACHED: 'DETACHED',
  DUPLEX: 'DUPLEX',
  PENTHOUSE: 'PENTHOUSE',
  LAND: 'LAND',
  COMMERCIAL: 'COMMERCIAL'
};

const RESIDENT_RELATIONSHIPS = {
  OWNER: 'OWNER',
  TENANT: 'TENANT'
};

const INVOICE_STATUS = {
  PENDING: 'PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

const COMPLAINT_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_PARTS: 'PENDING_PARTS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

const COMPLAINT_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
  EMERGENCY: 'EMERGENCY'
};

module.exports = {
  ACCESS_CONTROL_STATUS,
  ACCESS_CODE_TYPES,
  ACCESS_CODE_STATUS,
  PROPERTY_TYPES,
  RESIDENT_RELATIONSHIPS,
  INVOICE_STATUS,
  COMPLAINT_STATUS,
  COMPLAINT_PRIORITY
};
