const prisma = require('../lib/prisma');
const { ACCESS_CONTROL_STATUS, ACCESS_CODE_STATUS } = require('@estate-manager/shared/constants/status');
const { restrictAccessCodeSchema } = require('@estate-manager/shared/schemas');

exports.getUsers = async (req, res, next) => {
  try {
    const { role, search } = req.query;
    const where = {};

    if (role) where.role = role;
    if (search) {
      where.OR = [
        { firstName: { contains: search, mode: 'insensitive' } },
        { lastName: { contains: search, mode: 'insensitive' } },
        { email: { contains: search, mode: 'insensitive' } },
        { phone: { contains: search, mode: 'insensitive' } }
      ];
    }

    const users = await prisma.user.findMany({
      where,
      orderBy: { createdAt: 'desc' }
    });

    res.json({
      success: true,
      count: users.length,
      data: { users }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Super Admin Code Restriction Engine (Rules 11, 12, 13)
 * Restricts access code generation without locking resident out of billing/payments
 */
exports.restrictAccessCode = async (req, res, next) => {
  try {
    const { id } = req.params;
    const validated = restrictAccessCodeSchema.parse(req.body);

    const resident = await prisma.user.findUnique({ where: { id } });
    if (!resident) {
      return res.status(404).json({
        success: false,
        error: 'RESIDENT_NOT_FOUND',
        message: 'Resident account not found.'
      });
    }

    const updatedResident = await prisma.user.update({
      where: { id },
      data: {
        accessControlStatus: ACCESS_CONTROL_STATUS.DISABLED,
        restrictionReason: validated.reason,
        restrictedAt: new Date()
      }
    });

    // Invalidate all active codes generated by this resident
    await prisma.accessCode.updateMany({
      where: { residentId: id, status: ACCESS_CODE_STATUS.ACTIVE },
      data: { status: ACCESS_CODE_STATUS.RESTRICTED }
    });

    // Notification skipped — Notification model not in Prisma schema
    if (validated.notifyResident) {
      console.log(`Notification to resident ${id}: Access Code Generation Restricted. Reason: ${validated.reason}`);
    }

    // Write immutable audit log entry
    await prisma.auditLog.create({
      data: {
        action: 'RESTRICT_ACCESS_CODE',
        targetModel: 'User',
        targetId: id,
        details: {
          reason: validated.reason,
          previousStatus: ACCESS_CONTROL_STATUS.ENABLED,
          newStatus: ACCESS_CONTROL_STATUS.DISABLED
        },
        performedBy: req.user.id,
        ipAddress: req.ip,
        userAgent: req.headers['user-agent']
      }
    });

    res.json({
      success: true,
      message: 'Resident access code privileges restricted successfully.',
      data: {
        residentId: updatedResident.id,
        accessControlStatus: updatedResident.accessControlStatus,
        restrictionReason: updatedResident.restrictionReason
      }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Re-enable access code generation for resident
 */
exports.unrestrictAccessCode = async (req, res, next) => {
  try {
    const { id } = req.params;
    const resident = await prisma.user.findUnique({ where: { id } });
    if (!resident) {
      return res.status(404).json({
        success: false,
        error: 'RESIDENT_NOT_FOUND',
        message: 'Resident account not found.'
      });
    }

    const updatedResident = await prisma.user.update({
      where: { id },
      data: {
        accessControlStatus: ACCESS_CONTROL_STATUS.ENABLED,
        restrictionReason: null,
        restrictedAt: null
      }
    });

    // Notification skipped — Notification model not in Prisma schema
    console.log(`Notification to resident ${id}: Access Code Privileges Restored.`);

    await prisma.auditLog.create({
      data: {
        action: 'UNRESTRICT_ACCESS_CODE',
        targetModel: 'User',
        targetId: id,
        details: { restoredBy: req.user.id },
        performedBy: req.user.id
      }
    });

    res.json({
      success: true,
      message: 'Resident access code privileges restored successfully.',
      data: {
        residentId: updatedResident.id,
        accessControlStatus: updatedResident.accessControlStatus
      }
    });
  } catch (error) {
    next(error);
  }
};
