const User = require('../models/User');
const AccessCode = require('../models/AccessCode');
const Notification = require('../models/Notification');
const AuditLog = require('../models/AuditLog');
const { ACCESS_CONTROL_STATUS, ACCESS_CODE_STATUS } = require('@estate-manager/shared/constants/status');
const { restrictAccessCodeSchema } = require('@estate-manager/shared/schemas');

exports.getUsers = async (req, res, next) => {
  try {
    const { role, estateId, search } = req.query;
    const query = {};

    if (role) query.role = role;
    if (search) {
      query.$or = [
        { firstName: { $regex: search, $options: 'i' } },
        { lastName: { $regex: search, $options: 'i' } },
        { email: { $regex: search, $options: 'i' } },
        { phone: { $regex: search, $options: 'i' } }
      ];
    }

    const users = await User.find(query).sort({ createdAt: -1 });

    res.json({
      success: true,
      count: users.length,
      data: { users }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Super Admin Code Restriction Engine (Rules 11, 12, 13)
 * Restricts access code generation without locking resident out of billing/payments
 */
exports.restrictAccessCode = async (req, res, next) => {
  try {
    const { id } = req.params;
    const validated = restrictAccessCodeSchema.parse(req.body);

    const resident = await User.findById(id);
    if (!resident) {
      return res.status(404).json({
        success: false,
        error: 'RESIDENT_NOT_FOUND',
        message: 'Resident account not found.'
      });
    }

    resident.accessControlStatus = ACCESS_CONTROL_STATUS.DISABLED;
    resident.restrictionMetadata = {
      restrictedAt: new Date(),
      restrictedBy: req.user._id || req.user.id,
      reason: validated.reason
    };
    await resident.save();

    // Invalidate all active codes generated by this resident
    await AccessCode.updateMany(
      { residentId: resident._id, status: ACCESS_CODE_STATUS.ACTIVE },
      { status: ACCESS_CODE_STATUS.RESTRICTED }
    );

    // Create In-App Notification if requested
    if (validated.notifyResident) {
      await Notification.create({
        userId: resident._id,
        title: 'Access Code Generation Restricted',
        message: `Your guest access code generation privileges have been suspended. Reason: ${validated.reason}`,
        type: 'ACCESS_RESTRICTION',
        data: { reason: validated.reason }
      });
    }

    // Write immutable audit log entry
    await AuditLog.create({
      action: 'RESTRICT_ACCESS_CODE',
      targetModel: 'User',
      targetId: resident._id.toString(),
      details: {
        reason: validated.reason,
        previousStatus: ACCESS_CONTROL_STATUS.ENABLED,
        newStatus: ACCESS_CONTROL_STATUS.DISABLED
      },
      performedBy: (req.user._id || req.user.id).toString(),
      ipAddress: req.ip,
      userAgent: req.headers['user-agent']
    });

    res.json({
      success: true,
      message: 'Resident access code privileges restricted successfully.',
      data: {
        residentId: resident._id,
        accessControlStatus: resident.accessControlStatus,
        restrictionMetadata: resident.restrictionMetadata
      }
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Re-enable access code generation for resident
 */
exports.unrestrictAccessCode = async (req, res, next) => {
  try {
    const { id } = req.params;
    const resident = await User.findById(id);
    if (!resident) {
      return res.status(404).json({
        success: false,
        error: 'RESIDENT_NOT_FOUND',
        message: 'Resident account not found.'
      });
    }

    resident.accessControlStatus = ACCESS_CONTROL_STATUS.ENABLED;
    resident.restrictionMetadata = {
      restrictedAt: null,
      restrictedBy: null,
      reason: null
    };
    await resident.save();

    await Notification.create({
      userId: resident._id,
      title: 'Access Code Privileges Restored',
      message: 'Your gate access code creation privileges have been reinstated.',
      type: 'ACCESS_RESTRICTION'
    });

    await AuditLog.create({
      action: 'UNRESTRICT_ACCESS_CODE',
      targetModel: 'User',
      targetId: resident._id.toString(),
      details: { restoredBy: req.user._id || req.user.id },
      performedBy: (req.user._id || req.user.id).toString()
    });

    res.json({
      success: true,
      message: 'Resident access code privileges restored successfully.',
      data: {
        residentId: resident._id,
        accessControlStatus: resident.accessControlStatus
      }
    });
  } catch (error) {
    next(error);
  }
};
